
# Site settings
title: NGRAI
email: 
description: "All things AI and (potential) application areas in Nigeria."
baseurl: ""
url: "www.ngrai.org"
twitter_username: ngrai_
pagination: 10
disqus:
    shortname: ngrai

